/* eslint-disable no-undef */
const mockPrisma = {
  user: {
    findUnique: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    findMany: jest.fn(),
    count: jest.fn(),
  },
  emailVerification: {
    findUnique: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    deleteMany: jest.fn(),
  },
  passwordReset: {
    create: jest.fn(),
    findUnique: jest.fn(),
    update: jest.fn(),
  },
  doctor: {
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
  },
  patient: {
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
  },
  appointment: {
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    count: jest.fn(),
  },
  prescription: {
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
  },
  queueEntry: {
    findFirst: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  auditLog: {
    create: jest.fn(),
    findMany: jest.fn(),
    count: jest.fn(),
    groupBy: jest.fn(),
    deleteMany: jest.fn(),
  },
  dashboardConfig: {
    findUnique: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    upsert: jest.fn(),
  },
  permission: {
    findUnique: jest.fn(),
    findMany: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
    delete: jest.fn(),
  },
  rolePermission: {
    findMany: jest.fn(),
    create: jest.fn(),
    delete: jest.fn(),
    deleteMany: jest.fn(),
  },
  $transaction: jest.fn(),
  userSession: {
    create: jest.fn(),
    deleteMany: jest.fn(),
    findUnique: jest.fn(),
  },
  // allow spreading for other Prisma exports
}

module.exports = {
  prisma: mockPrisma,
  UserRole: {
    ADMIN: 'ADMIN',
    DOCTOR: 'DOCTOR',
    PATIENT: 'PATIENT',
    NURSE: 'NURSE',
  },
  AuthProvider: {
    LOCAL: 'LOCAL',
    GOOGLE: 'GOOGLE',
  },
  Gender: {
    MALE: 'MALE',
    FEMALE: 'FEMALE',
    OTHER: 'OTHER',
  },
  AppointmentStatus: {
    PENDING: 'PENDING',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    SCHEDULED: 'SCHEDULED',
    CONFIRMED: 'CONFIRMED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW',
  },
  ActivityType: {
    APPOINTMENT: 'APPOINTMENT',
    PRESCRIPTION: 'PRESCRIPTION',
    REPORT: 'REPORT',
  },
  NotificationType: {
    APPOINTMENT_REMINDER_24H: 'APPOINTMENT_REMINDER_24H',
    APPOINTMENT_REMINDER_1H: 'APPOINTMENT_REMINDER_1H',
    ACTIVITY_CREATED: 'ACTIVITY_CREATED',
    ACTIVITY_UPDATED: 'ACTIVITY_UPDATED',
    HEALTH_TIP_GENERATED: 'HEALTH_TIP_GENERATED',
  },
  QueueType: {
    WALK_IN: 'WALK_IN',
    ONLINE_BOOKING: 'ONLINE_BOOKING',
  },
  QueueStatus: {
    WAITING: 'WAITING',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW',
  },
  DoctorAvailabilityStatus: {
    AVAILABLE: 'AVAILABLE',
    BUSY: 'BUSY',
    BREAK: 'BREAK',
    OFF_DUTY: 'OFF_DUTY',
  },
  AuditAction: {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    TOKEN_REFRESH: 'TOKEN_REFRESH',
    FAILED_LOGIN: 'FAILED_LOGIN',
    PATIENT_HISTORY_ACCESS: 'PATIENT_HISTORY_ACCESS',
    DOCTOR_HISTORY_ACCESS: 'DOCTOR_HISTORY_ACCESS',
    APPOINTMENT_VIEW: 'APPOINTMENT_VIEW',
    MEDICAL_RECORD_VIEW: 'MEDICAL_RECORD_VIEW',
    PRESCRIPTION_VIEW: 'PRESCRIPTION_VIEW',
    REPORT_UPLOAD: 'REPORT_UPLOAD',
    REPORT_VIEW: 'REPORT_VIEW',
    PATIENT_CREATED: 'PATIENT_CREATED',
    PATIENT_UPDATED: 'PATIENT_UPDATED',
    PATIENT_DELETED: 'PATIENT_DELETED',
    APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
    APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
    APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
    PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
    PRESCRIPTION_UPDATED: 'PRESCRIPTION_UPDATED',
    DOCTOR_SEARCH: 'DOCTOR_SEARCH',
    APPOINTMENT_SEARCH: 'APPOINTMENT_SEARCH',
    PATIENT_SEARCH: 'PATIENT_SEARCH',
    USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
    PERMISSION_GRANTED: 'PERMISSION_GRANTED',
    PERMISSION_REVOKED: 'PERMISSION_REVOKED',
    PERMISSION_CREATED: 'PERMISSION_CREATED',
    PERMISSION_UPDATED: 'PERMISSION_UPDATED',
    PERMISSION_DELETED: 'PERMISSION_DELETED',
    PERMISSIONS_BULK_GRANTED: 'PERMISSIONS_BULK_GRANTED',
    PERMISSIONS_BULK_REVOKED: 'PERMISSIONS_BULK_REVOKED',
    PERMISSIONS_CLONED: 'PERMISSIONS_CLONED',
    UNAUTHORIZED_ACCESS_ATTEMPT: 'UNAUTHORIZED_ACCESS_ATTEMPT',
    SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
    MFA_SETUP_INITIATED: 'MFA_SETUP_INITIATED',
    MFA_ENABLED: 'MFA_ENABLED',
    MFA_DISABLED: 'MFA_DISABLED',
    MFA_VERIFIED: 'MFA_VERIFIED',
    MFA_VERIFICATION_FAILED: 'MFA_VERIFICATION_FAILED',
    MFA_BACKUP_CODES_REGENERATED: 'MFA_BACKUP_CODES_REGENERATED',
    QUEUE_ENTRY_ADDED: 'QUEUE_ENTRY_ADDED',
    QUEUE_ENTRY_REMOVED: 'QUEUE_ENTRY_REMOVED',
    QUEUE_ENTRY_STATUS_CHANGED: 'QUEUE_ENTRY_STATUS_CHANGED',
    QUEUE_ENTRY_REORDERED: 'QUEUE_ENTRY_REORDERED',
    QUEUE_CALLED_NEXT: 'QUEUE_CALLED_NEXT',
    QUEUE_CHECK_IN: 'QUEUE_CHECK_IN',
    DOCTOR_STATUS_CHANGED: 'DOCTOR_STATUS_CHANGED',
    DRUG_SEARCH: 'DRUG_SEARCH',
    DRUG_LOOKUP: 'DRUG_LOOKUP',
    INTERACTION_CHECK: 'INTERACTION_CHECK',
    INTERACTION_OVERRIDE: 'INTERACTION_OVERRIDE',
    ALLERGY_CHECK: 'ALLERGY_CHECK',
    ALLERGY_CONFLICT_OVERRIDE: 'ALLERGY_CONFLICT_OVERRIDE',
    ALLERGY_ADDED: 'ALLERGY_ADDED',
    ALLERGY_UPDATED: 'ALLERGY_UPDATED',
    ALLERGY_DELETED: 'ALLERGY_DELETED',
  },
  PermissionAction: {
    CREATE: 'CREATE',
    READ: 'READ',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    MANAGE: 'MANAGE',
    EXECUTE: 'EXECUTE',
  },
  InteractionSeverity: {
    HIGH: 'HIGH',
    MODERATE: 'MODERATE',
    LOW: 'LOW',
  },
  InteractionCheckStatus: {
    NOT_CHECKED: 'NOT_CHECKED',
    PASSED: 'PASSED',
    WARNINGS_ACKNOWLEDGED: 'WARNINGS_ACKNOWLEDGED',
    FAILED: 'FAILED',
  },
  MedicationRoute: {
    ORAL: 'ORAL',
    IV: 'IV',
    IM: 'IM',
    SUBCUTANEOUS: 'SUBCUTANEOUS',
    TOPICAL: 'TOPICAL',
    INHALATION: 'INHALATION',
    SUBLINGUAL: 'SUBLINGUAL',
    RECTAL: 'RECTAL',
    TRANSDERMAL: 'TRANSDERMAL',
    OPHTHALMIC: 'OPHTHALMIC',
    OTIC: 'OTIC',
    NASAL: 'NASAL',
    OTHER: 'OTHER',
  },
  AllergenType: {
    DRUG: 'DRUG',
    DRUG_CLASS: 'DRUG_CLASS',
    INGREDIENT: 'INGREDIENT',
    FOOD: 'FOOD',
    ENVIRONMENTAL: 'ENVIRONMENTAL',
    OTHER: 'OTHER',
  },
  AllergySeverity: {
    MILD: 'MILD',
    MODERATE: 'MODERATE',
    SEVERE: 'SEVERE',
    LIFE_THREATENING: 'LIFE_THREATENING',
  },
}
